### ISSUE TITLE
How to use docker_platform-devel ?

### ISSUE THREAD

**Issue by Alphapage** [phablet/docker_platform-devel#3]
Hello,

I have built the container from latest dockerfile, but now I'm lost:
which command to run and how to use the container to enable development ?

Thanks in advance for your help.

**Comment by vicamo** [comment]
Hi, sorry didn't notice the notifications.

Basically this is a repository hosting all the Ubuntu Touch platform development docker images. It means all the images here are used as the build environment when you're either porting or developing a new Ubuntu Touch based device. It's a build environment, just like the build environment your need for developing Android devices. So just execute `docker run -it <image name> /bin/bash` and it gives you a working environment for targeting device.
